name: Update Submodules

on:
  push:
    branches:
      - main

jobs:
  update-submodules:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Update submodules
        run: |
          git submodule init
          git submodule update --remote
          git commit -am "Updated submodules" || true
          git push origin main
