name: Update Submodules

on:
  push:
    branches:
      - main

jobs:
  update-submodules:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Update submodules
        run: |
          git config user.email "jayaram.krovvidi@outlook.com"
          git config user.name "Jayaram Krovvidi"
          git submodule update --remote
          git commit -am "Updated submodules" || true
          git push origin main
